### ISSUE TITLE
Snapshot operation not permitted

### ISSUE THREAD

**Issue by SjamonDaal** [45Drives/cephgeorep#44]
Hi,

I'm trying to setup cephgeorep but I can't get it to work.

Output:
```
$ cephfssyncd -d -s -v

Reading last rctime from disk.
Watching: /mnt/cephroot
Checking for change.
Change detected in /mnt/cephroot
Creating snapshot: /mnt/cephroot/.snap/2928286snapshot1643381222.476912000
Error: Error creating snapshot path: Operation not permitted
Removing snapshot: /mnt/cephroot/.snap/2928286snapshot1643381222.476912000
```

What permissions are required for the ceph user? Or that is the issue? I've created a new user and allowed * on all objects but still didn't work.

**Comment by bkelly16** [comment]
What is the contents of that users keyring ? 

You will need to either * the mds caps, or explicity give snapshot permission to the directory. 

For example, the below caps for a client.samba has only read access to the root of the cephfs filesystem. But has permission to:
- (r)ead
- (w)rite
- (p) set quota and data layout
- (s) create/delete snapshots

More info in the ceph docs's [here](https://docs.ceph.com/en/latest/cephfs/client-auth/#snapshot-restriction-the-s-flag)

```
client.samba
	key: AQB8tOphAAAAABAAgKYR8cR8HLliC2Rmu/0n3A==
	caps: [mds] allow r path=/, allow rwps path=/fsgw
	caps: [mon] allow r
	caps: [osd] allow *
```

**Comment by SjamonDaal** [comment]
I've tested cephgeorep with the following permissions:
```
client.admin
        key: 000==
        caps: [mds] allow *
        caps: [mgr] allow *
        caps: [mon] allow *
        caps: [osd] allow *
```

**Comment by SjamonDaal** [comment]
I've created a new user with the following auth but I still receive the same message.
```
client.cephfs-backup
        key: 000==
        caps: [mds] allow rws path=/
        caps: [mon] allow r
        caps: [osd] allow rw pool=cephfs_data
```

**Comment by SjamonDaal** [comment]
It's working now on our testing cluster but I can't get it to work on our production servers. Seems to be something ceph related. Is there a setting I need to enable before snapshots are enabled or something like that? I've tried
```
$ ceph mds set allow_new_snaps true
Error ENOTSUP: command is obsolete; please check usage and/or man page
```
Running ceph version 13.2.5 mimic

**Comment by SjamonDaal** [comment]
Fixed this issue. Solution: https://docs.ceph.com/en/mimic/dev/cephfs-snapshots/#creating-a-snapshot
